name-template: "v1.0.$NEXT_PATCH_VERSION"
tag-template: "v1.0.$NEXT_PATCH_VERSION"
change-template: "- $TITLE"
no-changes-template: "- Sin cambios registrados"

categories:
  - title: "Correcciones:"
    labels:
      - "Correcciones"
      - "Correccion"
      - "Corrección"
      - "Correcion"
      - "Corregido"
      - "Corregida"
      - "Corregidos"
      - "Corregidas"
      - "correccion"
      - "corrección"
      - "correcciones"
      - "correcion"
      - "corregido"
      - "corregida"
      - "corregidos"
      - "corregidas"
      - "fix"
      - "bug"
  - title: "Añadidos:"
    labels:
      - "Añadidos"
      - "Añadido"
      - "Anadido"
      - "Anadidos"
      - "Agregado"
      - "Agregados"
      - "añadido"
      - "añadidos"
      - "anadido"
      - "anadidos"
      - "agregado"
      - "agregados"
      - "add"
      - "added"
      - "feature"
      - "enhancement"
  - title: "Actualizaciones:"
    labels:
      - "Actualizaciones"
      - "Actualizacion"
      - "Actualización"
      - "Actualizado"
      - "Actualizada"
      - "Actualizados"
      - "Actualizadas"
      - "actualizado"
      - "actualizada"
      - "actualizacion"
      - "actualización"
      - "actualizaciones"
      - "actualizados"
      - "actualizadas"
      - "chore"
      - "maintenance"
      - "refactor"
  - title: "Otros"
    labels:
      - "misc"

template: |
  $CHANGES
